# ################################################################################## #
# +--------------------------------------------------------------------------------+ #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |                     __          __        ___       __                         | #
# |                    /__` | |\/| |__) |    |_        |_  |    \/                 | #
# |                    .__/ | |  | |    |___ |___      |   |___ /                  | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# |      Youtube:    www.youtube.com/@davigamer1614                                | #
# |      Github:     https://github.com/BEAMONDO/Minecraft-Plugin-SimpleFly        | #
# |                                                                                | #
# |                                                                                | #
# |                                                                                | #
# +--------------------------------------------------------------------------------+ #
# ################################################################################## #


#   help-message: enable or disable the command message "/sf help"
#   reload-message: enable or disable the command message "/sf reload"
#   version-message: enable or disable the command message "/sf version"
#   fly-message: enable or disable the command message "/fly" and "/fly <player>"
#   pay-to-fly: enable or disable the option to pay to fly (if enable is necessary the plugin Vault)
#   fly-price: amount to pay if use "/fly" command if (pay-to-fly) is enable
#   no-argument-message: enable or disable the command message "/sf" if it not have any argument
#   no-perm-message: enable or disable message when use a command and don`t have permission


Config:
  help-message: true
  reload-message: true
  version-message: true
  fly-message: true
  pay-to-fly: false
  fly-price: 1000
  no-argument-message: true
  no-perm-message: true