main: davigamer161.simplefly.SimpleFly
version: 1.4.1
name: SimpleFly
softdepend: [Vault]

commands:
  simplefly.*:
    default: op
    description: Todos los permisos
  fly:
    description: Comando para usar fly
  simplefly:
    description: Comando principal
    aliases: [sf]
permissions:
  simplefly.fly:
    description: Permiso uso fly
  simplefly.fly.others:
    description: Permiso uso fly a otros
  simplefly.help:
    description: Permiso uso help
  simplefly.reload:
    description: Permiso uso reload
  simplefly.version:
    description: Permiso uso version
  simplefly.econ.exempt:
    description: Sirve para no pagar al usar /fly
  simplefly.econ.exempt.others:
    description: Sirve para no pagar al usar /fly para otros